[google]
client_id = "1093447239111-4ofkik8lg55cjsd6j327mlop4tnkpil.apps.googleusercontent.com"
client_secret = "GOCSPX-h5agY9Hd1-60faJuz0SPqofCozf"
redirect_uris = ["https://ahorrosmart-hcj7adf9bqzss2nbrdpx3g.streamlit.app"]
